name: gogo_cookie_gen

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4
          
      - name: execute py script
        run: python assets/update.py

      - name: commit files
        run: |
          git config --local user.email ${{ secrets.MY_GIT_EMAIL }}
          git config --local user.name "junioralive"
          git add -A
          git commit -m "updated cookies" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
